In [1]:
import os

In [1]:
import pandas as pd
# Load dataset to a data frame
movies = pd.read_csv('./data/data_movie.csv')
movies.head()

,title,category,date_premiere,poster,director,content,trailer,average_rating,actor,crawled_at,url,_id
0,"10,000 Maniacs: Time Capsule 1982-1990",Music,1990-01-01,https://cps-static.rovicorp.com/1/avg/cov310/d...,NaN,With their thoughtful folk rock sound and lyri...,NaN,NaN,NaN,2021-05-02 20:30:29,https://www.allmovie.com/movie/10000-maniacs-t...,5b8e0dbb-3b48-5600-a544-651f9020245d
1,10 Rillington Place,"Crime, Drama",1971-02-10,https://cps-static.rovicorp.com/2/Open/Sony%20...,Richard Fleischer,10 Rillington Place is the true story of Briti...,https://video.internetvideoarchive.net/video.m...,8.1,"10 Rillington Place, Richard Attenborough, Jud...",02/05/2021 20:30:29,https://www.allmovie.com/movie/10-rillington-p...,2b5d82ef-2429-52fb-b5ab-ffbd7ede3c3b
2,10 Violent Women,"Action, Crime",1982-01-01,https://cps-static.rovicorp.com/2/Open/MovieDB...,Ted V. Mikels,This women's prison drama from exploitation fi...,NaN,1.3,"The Corpse Grinders, Sherri Vernon",2021-05-02 20:30:29,https://www.allmovie.com/movie/10-violent-wome...,be7268a9-41c0-57a3-b057-8d8e6cb8ab2e
3,10,Comedy,1979-10-05,https://cps-static.rovicorp.com/2/Open/Warner_...,Blake Edwards,Blake Edwards' 10 stars Dudley Moore as George...,https://video.internetvideoarchive.net/video.m...,6.5,"Mancini, Dudley Moore, Maurice Ravel, Sam Jone...",2021-05-02 20:30:29,https://www.allmovie.com/movie/10-v5,f9b28fb4-d19f-50c1-91e3-78afd7f3a4fd
4,100 Rifles,Western,1969-03-26,https://cps-static.rovicorp.com/2/Open/20th%20...,Tom Gries,Lyedecker (Jim Brown) is the Arizona lawman wh...,https://video.internetvideoarchive.net/video.m...,4.1,"Burt Reynolds, Dan O'Herlihy, Jim Brown, Raque...",2021-05-02 20:30:30,https://www.allmovie.com/movie/100-rifles-v16,26149137-9e75-5fdd-9bd8-a26ada38c38d

In [ ]:
ratings = pd.DataFrame(df.groupby('title')['rating'].mean())

In [14]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [15]:
import re

def clean_title(title):
    return re.sub("[^a-zA-Z0-9 ]", "", title)

In [16]:
movies["clean_title"] = movies["title"].apply(clean_title)

In [17]:
movies

,movieId,title,genres,clean_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Toy Story 1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,Jumanji 1995
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men 1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Waiting to Exhale 1995
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II 1995
...,...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,Black Butler Book of the Atlantic 2017
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,No Game No Life Zero 2017
9739,193585,Flint (2017),Drama,Flint 2017
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,Bungo Stray Dogs Dead Apple 2018
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,Andrew Dice Clay Dice Rules 1991

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(ngram_range=(1,2))
tfidf = vectorizer.fit_transform(movies["clean_title"])

In [19]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def search(title):
    title = "Toy Story 1995"
    title = clean_title(title)
    query_vec = vectorizer.transform([title])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    results = movies.iloc[indices][::-1]
    return results

In [20]:
# Building an interactive search box with Jupyter
import ipywidgets as widgets
from IPython.display import display

movie_input=widgets.Text(
    value='Toy Story',
    description = "Movie Title",
    disabled=False)

movie_list = widgets.Output()

def on_type(data):
    with movie_list:
        movie_list.clear_output()
        title = data["new"]
        if len(title) > 5:
            display(search(title))

movie_input.observe(on_type, names = 'value')

display(movie_input, movie_list)

ModuleNotFoundError: No module named 'ipywidgets'

In [44]:
# Reading in movie ratings data
ratings = pd.read_csv('/content/ratings.csv')
ratings

# print(combined_features)

,movieId,title,genres,clean_title
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,ToyStory1995
3247,4389,Lost and Delirious (2001),Drama,LostandDelirious2001
3246,4388,Scary Movie 2 (2001),Comedy,ScaryMovie22001
3249,4392,Alice (1990),Comedy|Drama|Fantasy|Romance,Alice1990
3252,4395,Big Deal on Madonna Street (I Soliti Ignoti) (...,Comedy|Crime,BigDealonMadonnaStreetISolitiIgnoti1958

In [13]:
# Finding users who liked the same movie
ratings.dtypes

(9742, 4)

In [6]:
movie_id=1
similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings['rating'] > 4)]["userId"].unique()
similar_users_recs = ratings[(ratings["userId"].isin(similar_users)) & (ratings['rating'] > 4)]["movieId"]
similar_users_recs

,movieId,genres,title
0,1,Adventure|Animation|Children|Comedy|Fantasy,Toy Story (1995)
1,2,Adventure|Children|Fantasy,Jumanji (1995)
2,3,Comedy|Romance,Grumpier Old Men (1995)
3,4,Comedy|Drama|Romance,Waiting to Exhale (1995)
4,5,Comedy,Father of the Bride Part II (1995)

In [ ]:
similar_users_recs = similar_users_recs.value_counts()/len(similar_users)
similar_users_recs = similar_users_recs[similar_users_recs > .1]
similar_users_recs

In [7]:
# Finding how much all users like movies
all_users = ratings[(ratings["movieId"].isin(similar_users_recs.index)) & (ratings['rating'] > 4)]

['(no genres listed)',
 'Action',
 'Adventure',
 'Animation',
 'Children',
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'IMAX',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [8]:
all_users_recs = all_users["movieId"].value_counts()/len(all_users["userId"].unique())
all_users_recs

20

In [ ]:
rec_percentages = pd.concat([similar_users_recs, all_users_recs], axis = 1)
rec_percentages

In [ ]:
rec_percentages.columns = ["similar", "all"]
rec_percentages

In [16]:
rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
rec_percentages = rec_percentages.sort_values ("score", ascending = False)
rec_percentages

In [17]:
rec_percentages.head(10).merge(movies, left_index = True, right_on = "movieId")

      movieId                                       genres
0           1  Adventure|Animation|Children|Comedy|Fantasy  \
1           2                   Adventure|Children|Fantasy
2           3                               Comedy|Romance
3           4                         Comedy|Drama|Romance
4           5                                       Comedy
...       ...                                          ...
9737   193581              Action|Animation|Comedy|Fantasy
9738   193583                     Animation|Comedy|Fantasy
9739   193585                                        Drama
9740   193587                             Action|Animation
9741   193609                                       Comedy

                                          title
0                              Toy Story (1995)
1                                Jumanji (1995)
2                       Grumpier Old Men (1995)
3                      Waiting to Exhale (1995)
4            Father of the Bride Part II (1995)
...                                         ...
9737  Black Butler: Book of the Atlantic (2017)
9738               No Game No Life: Zero (2017)
9739                               Flint (2017)
9740        Bungo Stray Dogs: Dead Apple (2018)
9741        Andrew Dice Clay: Dice Rules (1991)

[9742 rows x 3 columns]

In [18]:
# Bulding a recommendation function
def find_similar_movies(movie_id):
  similar_users = ratings[(ratings["movieId"] == movie_id) & (ratings['rating'] > 4)]["userId"].unique()
  similar_users_recs = ratings[(ratings["userId"].isin(similar_users)) & (ratings['rating'] > 4)]["movieId"]
  
  similar_users_recs = similar_users_recs.value_counts()/len(similar_users)
  similar_users_recs = similar_users_recs[similar_users_recs > .10]
  
  all_users = ratings[(ratings["movieId"].isin(similar_users_recs.index)) & (ratings['rating'] > 4)]
  all_users_recs = all_users["movieId"].value_counts()/len(all_users["userId"].unique())
  
  rec_percentages = pd.concat([similar_users_recs, all_users_recs], axis = 1)
  rec_percentages.columns = ["similar", "all"]
  
  rec_percentages["score"] = rec_percentages["similar"] / rec_percentages["all"]
  
  rec_percentages = rec_percentages.sort_values ("score", ascending = False)
  return rec_percentages.head(10).merge(movies, left_index = True, right_on = "movieId")[["score", "title", "genres"]]

In [21]:
# Creating an interactive recommendation widget
movie_input_name = widgets.Text(
    value='Toy Story',
    description = "Movie Title",
    disabled=False)

recommendation_list = widgets.Output()

def on_type(data):
    with recommendation_list:
        recommendation_list.clear_output()
        title = data["new"]
        if len(title) > 5:
          results = search(title)
          movie_id = results.iloc[0]["movieId"]
          display(find_similar_movies(movie_id))

movie_input_name.observe(on_type, names = 'value')

display(movie_input_name, recommendation_list)